# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'factorial', 'DoStuff']

# Cell
def say_hello(to):
    "Say hello"
    return f"Hello {to}"

# Cell
def factorial(n):
    if n == 1:
        return 1
    else:
        return n*factorial(n-1)

# Cell
class DoStuff:
    "Say hello and do some factorials"
    def __init__(self, to, val):
        self.to = to
        self.val = val

    def say(self):
        "Say something"
        return say_hello(self.to)
    def get_fact(self):
        "Get factorial"
        return factorial(self.val)