# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'factorial']

# Cell
def say_hello(to):
    "Say hello"
    return f"Hello {to}"

# Cell
def factorial(n):
    if n == 1:
        return 1
    else:
        return n*factorial(n-1)